name: Build & Push Docker Images

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-central-1
  ECR_REGISTRY: 471112976468.dkr.ecr.eu-central-2.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push backend
        run: |
          docker build -t text-to-sql-backend ./text-to-sql
          docker tag text-to-sql-backend:latest $ECR_REGISTRY/text-to-sql-backend:latest
          docker push $ECR_REGISTRY/text-to-sql-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t text-to-sql-frontend ./text-to-sql-frontend
          docker tag text-to-sql-frontend:latest $ECR_REGISTRY/text-to-sql-frontend:latest
          docker push $ECR_REGISTRY/text-to-sql-frontend:latest

